# must me the same as the folder name of the project
name = "example-r2-multipart-upload"
main = "src/index.js"
# use current date 
compatibility_date = "2024-05-07" 
compatibility_flags = ["nodejs_compat"]


[vars]
R2_ACCESS_KEY_ID = "<your access key id>"
R2_SECRET_ACCESS_KEY = "<your secret access key>"
# uner "jurisdiction-specific endpoints for S3 clients" when creating the api key
CF_ENDPOINT = "<your endpoint url>"